name: ben.cook.qr
channels:
  - conda-forge
  - defaults
  - http://swrepo.akunacapital.local/pyrepo/v3/repo/dev
  - http://swrepo.akunacapital.local/pyrepo/v3/repo/prod
  - http://swrepo.akunacapital.local/pyrepo/v3/repo/third_party
dependencies:
  # General purpose
  - python=3.6.8
  - anaconda
  - jupyterlab
  - bokeh
  - ca-certificates
  - tqdm
  - pip
  # Akuna-specific
  - basilisk>=3.3.3
  - chainlink>=0.7.4
  - ddo>=4.92.0
  - ddo_utils>=8.0.2
  - encodediid2
  - hdal>=9.50.1
  - pricing_data>=4.3.6
  - pyrametron
  - pysolace
  - stores>=5.1.4
  - vol_research>=0.5.1
  - vsq_data>=0.4.0
  # Ben Optional
  - appmode
  - black=19.10b0
  - emacs>=26.3
  - jupyterlab_code_formatter
  - jupyterlab-git
  - sprockets
  - pathlib
  # For Dependency Reasons
  - black_mamba=2.28.4  # until ubuntu upgraded
  - h2=3.1.1  # hack, dependency issue with hdal
  - numpy=1.17.*  # vader issues
  - numpy-base=1.17.*  # vader issues
  # Pip
  - pip:
    - nbresuse
    - corner
    - black-macchiato==1.1.0
    - dataframe_image