name: ben.cook
channels:
  - conda-forge
  - defaults
dependencies:
  # General purpose
  - python=3.6.*
  - anaconda
  - jupyterlab
  - bokeh
  - ca-certificates
  - tqdm
  - pip
  # Ben Optional
  - appmode
  - black=19.10b0
  - emacs>=26.3
  - jupyterlab_code_formatter
  - jupyterlab-git
  - pathlib
  # Pip
  - pip:
    - nbresuse
    - corner
    - black-macchiato==1.1.0
