name: ben.cook.bqr_py36
channels:
  - conda-prod
  - conda-forge-remote
  - conda-thirdparty
  - defaults
dependencies:
  # General Purpose
  - python=3.6.8
  - anaconda
  - appmode
  - black
  - bokeh
  - ca-certificates
  - emacs
  - git
  - ipympl
  - jupyterlab>=3.0
  - pip
  # Akuna-specific
  - black_mamba>=3.2.3
  - boston_tasks
  - dataframe_tools>=0.5.0
  - ddo
  - ddo_utils>=8.38.2
  - hdal
  - pricing_data>=4.5.3
  - presto-client=0.300.0
  - pyrametron
  - vader=1.0.1
  - val_data>=2.3.0
  - vol_research>=1.0.2
  - vsq_data>=0.13.0
  # Ben Optional
  - jupyterlab_code_formatter
  - jupyter-resource-usage
  # - jupyterlab-git
  - pathlib
  - sprockets
  # For Dependency Reasons
  # Pip
  - pip:
    - corner
    - black-macchiato
    - aquirdturtle_collapsible_headings
    - jupyterlab-git==0.30.0b1
    